[package]
name = "fast_ttt"
version = "0.1.0"
license = "Unlicense"
edition = "2024"

[dependencies]
rand = { version = "0.9.1", features = ["small_rng"] }
rand_xoshiro = "0.7.0"

[profile.release-prod]
inherits = "release"
lto = "fat"
strip = true
codegen-units = 1
panic = "abort"
